In [1]:
training_dir = r"B:\jupyternotebook\mlboot\mlprojectpipelines\tutorial1\tutorial_project\housing\artifact\data_ingestion\2022-50-03_13-50-06\ingested_data\train\housing.csv"
training_dir

'B:\\jupyternotebook\\mlboot\\mlprojectpipelines\\tutorial1\\tutorial_project\\housing\\artifact\\data_ingestion\\2022-50-03_13-50-06\\ingested_data\\train\\housing.csv'

In [2]:
import pandas as pd

In [45]:
df = pd.read_csv(training_dir)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -118.20     33.93                36.0       2210.0           634.0   
1        -122.07     37.36                21.0       3244.0           426.0   
2        -121.49     38.49                26.0       1557.0           301.0   
3        -118.37     33.95                 5.0       6955.0          2062.0   
4        -117.61     34.13                21.0       8416.0          1386.0   
...          ...       ...                 ...          ...             ...   
16507    -118.24     34.01                30.0        405.0            86.0   
16508    -117.23     32.99                17.0       2718.0           326.0   
16509    -122.38     40.58                34.0       1262.0           267.0   
16510    -118.43     33.83                19.0       6206.0          1611.0   
16511    -119.06     35.33                14.0       5264.0          1064.0   

       population  households  median_income  median_house_value  \
0          2341.0       553.0         2.1715            131100.0   
1          1158.0       415.0         7.5000            500001.0   
2           986.0       300.0         2.6613             77700.0   
3          3591.0      1566.0         3.1110            247600.0   
4          4308.0      1341.0         4.4611            164600.0   
...           ...         ...            ...                 ...   
16507       376.0        68.0         1.7813            127500.0   
16508      1011.0       319.0        15.0001            500001.0   
16509       520.0       259.0         1.6983             72600.0   
16510      2455.0      1472.0         5.1450            420200.0   
16511      3278.0      1049.0         3.8117             82800.0   

      ocean_proximity  
0           <1H OCEAN  
1           <1H OCEAN  
2              INLAND  
3           <1H OCEAN  
4              INLAND  
...               ...  
16507       <1H OCEAN  
16508      NEAR OCEAN  
16509          INLAND  
16510      NEAR OCEAN  
16511          INLAND  

[16512 rows x 10 columns]

In [4]:
x,y = df.drop(columns=["median_house_value"],axis=1),df[["median_house_value"]]

In [5]:
x.shape,y.shape

((16512, 9), (16512, 1))

In [6]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        172
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [7]:
from sklearn.impute import SimpleImputer
s = SimpleImputer(strategy="median")

In [8]:
numerical_values = x.drop(columns=["ocean_proximity"],axis=1)
numerical_values

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -118.20     33.93                36.0       2210.0           634.0   
1        -122.07     37.36                21.0       3244.0           426.0   
2        -121.49     38.49                26.0       1557.0           301.0   
3        -118.37     33.95                 5.0       6955.0          2062.0   
4        -117.61     34.13                21.0       8416.0          1386.0   
...          ...       ...                 ...          ...             ...   
16507    -118.24     34.01                30.0        405.0            86.0   
16508    -117.23     32.99                17.0       2718.0           326.0   
16509    -122.38     40.58                34.0       1262.0           267.0   
16510    -118.43     33.83                19.0       6206.0          1611.0   
16511    -119.06     35.33                14.0       5264.0          1064.0   

       population  households  median_income  
0          2341.0       553.0         2.1715  
1          1158.0       415.0         7.5000  
2           986.0       300.0         2.6613  
3          3591.0      1566.0         3.1110  
4          4308.0      1341.0         4.4611  
...           ...         ...            ...  
16507       376.0        68.0         1.7813  
16508      1011.0       319.0        15.0001  
16509       520.0       259.0         1.6983  
16510      2455.0      1472.0         5.1450  
16511      3278.0      1049.0         3.8117  

[16512 rows x 8 columns]

In [9]:
df =s.fit_transform(numerical_values)
df

array([[-1.1820e+02,  3.3930e+01,  3.6000e+01, ...,  2.3410e+03,
         5.5300e+02,  2.1715e+00],
       [-1.2207e+02,  3.7360e+01,  2.1000e+01, ...,  1.1580e+03,
         4.1500e+02,  7.5000e+00],
       [-1.2149e+02,  3.8490e+01,  2.6000e+01, ...,  9.8600e+02,
         3.0000e+02,  2.6613e+00],
       ...,
       [-1.2238e+02,  4.0580e+01,  3.4000e+01, ...,  5.2000e+02,
         2.5900e+02,  1.6983e+00],
       [-1.1843e+02,  3.3830e+01,  1.9000e+01, ...,  2.4550e+03,
         1.4720e+03,  5.1450e+00],
       [-1.1906e+02,  3.5330e+01,  1.4000e+01, ...,  3.2780e+03,
         1.0490e+03,  3.8117e+00]])

In [10]:
s.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [11]:
s.statistics_#median value for all the columns :)

array([-118.49   ,   34.25   ,   29.     , 2126.     ,  433.     ,
       1163.     ,  409.     ,    3.53875])

In [12]:
x.fillna()

ValueError: Must specify a fill 'value' or 'method'.

In [ ]:
class FeatureGenerator:

    def __init__(self,strategy:str = "Median"):
        self.strategy = strategy
    
    def fit(self,x):
        self.features_ = x.columns
        self.statistics_ = []
        for col in x.columns:
            self.statistics_.append(x[col].median())
        
    def transform(self,x,is_inplace=True):
        for index,col in enumerate(x.columns):
            x[col].fillna(self.statistics_[index],inplace = is_inplace)
        return x
    
    def fit_transform(self,x):
        self.fit(x)
        return self.transform(x)


In [37]:
numerical_values = x.drop(columns=["ocean_proximity"],axis=1)
numerical_values.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        172
population              0
households              0
median_income           0
dtype: int64

In [ ]:
f = FeatureGenerator()
f.fit_transform(numerical_values)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -118.20     33.93                36.0       2210.0           634.0   
1        -122.07     37.36                21.0       3244.0           426.0   
2        -121.49     38.49                26.0       1557.0           301.0   
3        -118.37     33.95                 5.0       6955.0          2062.0   
4        -117.61     34.13                21.0       8416.0          1386.0   
...          ...       ...                 ...          ...             ...   
16507    -118.24     34.01                30.0        405.0            86.0   
16508    -117.23     32.99                17.0       2718.0           326.0   
16509    -122.38     40.58                34.0       1262.0           267.0   
16510    -118.43     33.83                19.0       6206.0          1611.0   
16511    -119.06     35.33                14.0       5264.0          1064.0   

       population  households  median_income  
0          2341.0       553.0         2.1715  
1          1158.0       415.0         7.5000  
2           986.0       300.0         2.6613  
3          3591.0      1566.0         3.1110  
4          4308.0      1341.0         4.4611  
...           ...         ...            ...  
16507       376.0        68.0         1.7813  
16508      1011.0       319.0        15.0001  
16509       520.0       259.0         1.6983  
16510      2455.0      1472.0         5.1450  
16511      3278.0      1049.0         3.8117  

[16512 rows x 8 columns]

In [ ]:
f.statistics_

[-118.49, 34.25, 29.0, 2126.0, 433.0, 1163.0, 409.0, 3.5387500000000003]

In [ ]:
# f.transform(numerical_values,True).isnull().sum()

In [ ]:
numerical_values.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [13]:
import numpy as np

In [132]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"

from sklearn.base import BaseEstimator,TransformerMixin

class FeatureGenerator(BaseEstimator,TransformerMixin):

    def __init__(self,add_bedrooms_per_room=True,total_room_ix=3,population_ix = 5,households_ix = 6,total_bedrooms_ix=4,
    columns=None):
        try:
            self.columns = columns
            # if self.columns is not None:
            #     print(self.columns)
            #     total_room_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
            #     population_ix = self.columns.index(COLUMN_POPULATION)
            #     households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
            #     total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_room_ix = total_room_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
        except Exception as e:
            raise e

    def fit(self,x,y=None):
        return self
    
    def transform(self,x,y=None):
        try:
            room_per_household = x[:,self.total_room_ix] / x[:,self.households_ix]
            population_per_household = x[:,self.population_ix]/x[:,self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = x[:,self.total_bedrooms_ix]/x[:,self.total_room_ix]
                generated_feature = np.c_[x,room_per_household,population_per_household,bedrooms_per_room]
            else:
                generated_feature = np.c_[x,room_per_household,population_per_household]
            
            return generated_feature

        except Exception as e:
            raise e

In [134]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [135]:
num_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy="median")),("feature_generator",FeatureGenerator()),
                                ('scaling',StandardScaler())])
num_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('feature_generator', FeatureGenerator()),
                ('scaling', StandardScaler())])

In [136]:
from sklearn.preprocessing import OneHotEncoder

In [137]:
cat_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy="most_frequent")),
('OnehotEncoder',OneHotEncoder()),('scaling',StandardScaler(with_mean=False))])
cat_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('OnehotEncoder', OneHotEncoder()),
                ('scaling', StandardScaler(with_mean=False))])

In [138]:
numerical_valuesd = list(numerical_values.drop(columns=["median_income"],axis=1).columns)
numerical_valuesd

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households']

In [139]:
categorical_values = list(x[["ocean_proximity"]].columns)
categorical_values

['ocean_proximity']

In [140]:
preprocessing = ColumnTransformer([('num_pipeline',num_pipeline,numerical_valuesd),
                                    ('cat_pipeline',cat_pipeline,categorical_values)])
preprocessing

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('feature_generator',
                                                  FeatureGenerator()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OnehotEncoder',
                                                  OneHotEncoder()),
                                                 ('scaling',
                                                  StandardScaler(with_mean=False))]),
                                 ['ocean_proximity'])])

In [141]:
preprocessing.fit_transform(df)

array([[ 0.68340291, -0.79413132,  0.58450757, ...,  0.        ,
         0.        ,  0.        ],
       [-1.24650632,  0.80852394, -0.61145141, ...,  0.        ,
         0.        ,  0.        ],
       [-0.95726928,  1.3365124 , -0.21279842, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.40109853,  2.31305744,  0.42504637, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56870546, -0.84085596, -0.77091261, ...,  0.        ,
         0.        ,  2.96446198],
       [ 0.25453419, -0.13998632, -1.1695656 , ...,  0.        ,
         0.        ,  0.        ]])

In [142]:
t_dir = r"B:\jupyternotebook\mlboot\mlprojectpipelines\tutorial1\tutorial_project\housing\artifact\data_ingestion\2022-41-03_13-41-11\ingested_data\test\housing.csv"
t_df= pd.read_csv(t_dir)

In [143]:
preprocessing.transform(t_df)

array([[ 0.26450788, -0.65862985, -0.8506432 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.31133531,  0.99542251,  0.66423816, ...,  0.        ,
         3.16000348,  0.        ],
       [-1.12183518,  0.83655872, -1.2492962 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.24650632,  0.91131815, -1.0101044 , ...,  0.        ,
         3.16000348,  0.        ],
       [-1.15175626,  0.79917901,  1.86019714, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.65846868, -0.78478639, -0.05333722, ...,  0.        ,
         0.        ,  0.        ]])

In [149]:
import dill 
with open("preprocessing.pkl","wb") as pre_file:
    dill.dump(preprocessing,pre_file)

In [150]:
os.path.dirname(t_dir)

'B:\\jupyternotebook\\mlboot\\mlprojectpipelines\\tutorial1\\tutorial_project\\housing\\artifact\\data_ingestion\\2022-41-03_13-41-11\\ingested_data\\test'